import User from "../models/User.js";
import createHttpError from "http-errors";
import validator from "validator";
import bcrypt from "bcryptjs";

// Utility to flatten nested objects into dot-notation keys
const flattenObject = (obj, prefix = "") => {
  return Object.keys(obj).reduce((acc, key) => {
    const newKey = prefix ? `${prefix}.${key}` : key;
    if (
      typeof obj[key] === "object" &&
      obj[key] !== null &&
      !Array.isArray(obj[key])
    ) {
      return { ...acc, ...flattenObject(obj[key], newKey) };
    }
    return { ...acc, [newKey]: obj[key] };
  }, {});
};

// Get authenticated user's profile
export const getMyProfile = async (req, res, next) => {
  try {
    const user = await User.findById(req.user._id)
      .select("+password")
      .populate("adminLogs.targetUser", "username");
    if (!user) return next(createHttpError(404, "User not found"));

    res.json({ success: true, data: user });
  } catch (err) {
    next(err);
  }
};

// Update authenticated user's profile
export const updateMyProfile = async (req, res, next) => {
  try {
    const { _id: userId, role } = req.user;
    const updates = req.body;

    // Define fields that can be updated by role
    const allowedFields = {
      common: [
        "username",
        "email",
        "password",
        "profile.avatar.url",
        "profile.avatar.public_id",
        "profile.phone",
        "profile.bio",
        "profile.address.street",
        "profile.address.city",
        "profile.address.state",
        "profile.address.zip",
        "profile.address.country",
        "profile.socialMedia.website",
        "profile.socialMedia.linkedin",
        "profile.socialMedia.twitter",
      ],
      worker: [
        "workerApplication.skills",
        "workerApplication.certifications",
        "workerApplication.experience",
        "workerApplication.documents",
        "workerApplication.workHistory",
        "workerApplication.availability",
      ],
      admin: [], // Admins can update common fields only
    };

    // Combine allowed fields based on role
    const permittedFields = [
      ...allowedFields.common,
      ...(allowedFields[role] || []),
    ];

    // Flatten nested updates
    const flattenedUpdates = flattenObject(updates);

    // Filter updates to only allowed fields
    const filteredUpdates = {};
    for (const key of Object.keys(flattenedUpdates)) {
      if (permittedFields.includes(key)) {
        filteredUpdates[key] = flattenedUpdates[key];
      }
    }

    // Validation map
    const validationRules = {
      email: {
        validator: validator.isEmail,
        message: "Invalid email",
      },
      "profile.phone": {
        validator: validator.isMobilePhone,
        message: "Invalid phone number",
      },
      "profile.address.zip": {
        validator: validator.isNumeric,
        message: "Invalid ZIP code",
      },
      "profile.socialMedia.website": {
        validator: validator.isURL,
        message: "Invalid website URL",
      },
      "profile.socialMedia.linkedin": {
        validator: validator.isURL,
        message: "Invalid LinkedIn URL",
      },
      "profile.socialMedia.twitter": {
        validator: validator.isURL,
        message: "Invalid Twitter URL",
      },
      "profile.avatar.url": {
        validator: (url) => {
          const baseUrl = process.env.BASE_URL || "http://localhost:5000";
          // Allow local upload URLs without strict validation
          if (url.startsWith(`${baseUrl}/uploads`)) {
            return true; // Trust URLs generated by localImageUpload
          }
          // Validate external URLs with lenient options
          return validator.isURL(url, {
            require_valid_protocol: true,
            protocols: ["http", "https"],
            require_tld: true,
          });
        },
        message: "Invalid avatar URL",
      },
    };

    // Validate fields
    for (const [field, { validator: validateFn, message }] of Object.entries(
      validationRules
    )) {
      if (filteredUpdates[field] && !validateFn(filteredUpdates[field])) {
        return next(createHttpError(400, message));
      }
    }

    // Special validation for avatar public_id and local uploads
    if (filteredUpdates["profile.avatar.url"]) {
      if (
        filteredUpdates["profile.avatar.public_id"] &&
        typeof filteredUpdates["profile.avatar.public_id"] !== "string"
      ) {
        return next(createHttpError(400, "Invalid avatar public_id"));
      }
      const baseUrl = process.env.BASE_URL || "http://localhost:5000";
      if (
        filteredUpdates["profile.avatar.url"].startsWith(
          `${baseUrl}/uploads`
        ) &&
        !filteredUpdates["profile.avatar.public_id"]
      ) {
        return next(
          createHttpError(400, "public_id required for local upload avatar")
        );
      }
    }

    // Handle password update
    if (filteredUpdates.password) {
      if (filteredUpdates.password.length < 6) {
        return next(
          createHttpError(400, "Password must be at least 6 characters")
        );
      }
      const salt = await bcrypt.genSalt(12);
      filteredUpdates.password = await bcrypt.hash(
        filteredUpdates.password,
        salt
      );
    }

    // Check for unique constraints
    if (filteredUpdates.username) {
      const existingUser = await User.findOne({
        username: filteredUpdates.username,
        _id: { $ne: userId },
      });
      if (existingUser)
        return next(createHttpError(400, "Username already taken"));
    }
    if (filteredUpdates.email) {
      const existingUser = await User.findOne({
        email: filteredUpdates.email,
        _id: { $ne: userId },
      });
      if (existingUser)
        return next(createHttpError(400, "Email already taken"));
    }
    if (filteredUpdates["profile.phone"]) {
      const existingUser = await User.findOne({
        "profile.phone": filteredUpdates["profile.phone"],
        _id: { $ne: userId },
      });
      if (existingUser)
        return next(createHttpError(400, "Phone number already taken"));
    }

    console.log("updates", updates);
    console.log("filteredUpdates", filteredUpdates);

    // Update user
    const user = await User.findByIdAndUpdate(
      userId,
      { $set: filteredUpdates },
      { new: true, runValidators: true }
    ).select("+password");

    if (!user) return next(createHttpError(400, "User not found"));

    res.json({ success: true, data: user });
  } catch (err) {
    next(err);
  }
};
